platform :ios, '7.0'

target 'BabyBrezza' do
    
pod 'MJExtension', '~> 2.1.0'
pod 'SVProgressHUD', '~> 1.1.3'
pod 'CPPickerView', '~> 1.2.0'
pod 'Masonry', '~> 0.6.4'
pod 'ReactiveCocoa', '2.5'
pod 'JJHelper', '2.5'

end
